service: pdf-generator

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: customer-profile
  region: sa-east-1
  iamRoleStatements:
    - Effect:  Allow
      Action: 
        - s3:GetObject
        - s3:PutObject
      Resource: 
        - "arn:aws:s3:::*"


functions:
  generator:
    handler: generator.handle
    environment:
      bucket: serverless
    events:
      - s3:
          bucket: serverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .pdf
    